pool:
  vmImage: 'Ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  dotnetVersion: 2.1.505
  webappRootDir: 'Tailspin.SpaceGame.Web/wwwroot'

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .Net Core'
    inputs:
      version: $(dotnetVersion)
    
  - task: Npm@1
    displayName: 'Run NPM'
    inputs:
      verbose: false

  - script: './node_modules/.bin/node-sass $(webappRootDir) --output $(webappRootDir)'
    displayName: Compile Saas
  
  - task: Gulp@1
    displayName: 'Run Gulp'
  
  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build info'
    workingDirectory: $(webappRootDir)

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dep'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build $(buildConfiguration) project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore --configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish $(buildConfiguration)'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeeded()