parameters: 
  buildConfiguration: ''

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore project dep'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build ${{buildConfiguration}} project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore --configuration ${{buildConfiguration}}'

  - task: DotNetCoreCLI@2
    displayName: 'Publish ${{buildConfiguration}}'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration ${{buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      zipAfterPublish: true